
version: 2.1

orbs:
  move-ci: moverdc/move-ci@3.4.0

executors:
  default:
    docker:
      - image: cimg/node:20.18
    working_directory: ~/twilio-voice-react-native

jobs:
  setup_workspace:
    executor: default
    steps:
      - checkout
      - move-ci/aws-proxy-up:
          configure-yarn3: true
          export-proxy-variables: http
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - move-ci/aws-proxy-down
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_package:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - move-ci/gh-install
      - move-ci/aws-proxy-up:
          configure-yarn3: true
          export-proxy-variables: http
      - move-ci/aws-codeartifact-auth:
          account: ${AWS_ACCOUNT_RDC_DEV}
          write-access: true
          tool: npm
      - run:
          name: Install packaging deps
          command: |
            sudo apt-get update
            sudo apt-get install rsync
      - run:
          name: Prepare package for publish
          command: yarn prepare
      - run:
          name: Publish npm package to AWS Code Artifact
          command: yarn release --ci
      - move-ci/aws-proxy-down

workflows:
  publish_package:
    jobs:
      - setup_workspace:
          context:
            - aws
      - deploy_package:
          context:
            - aws
            - github
          requires:
            - setup_workspace

